const ROUTINE = {
  1: {
    label: 'Semana 1',
    libres: [1, 2],
    dias: [
      { nombre: 'Lunes', tag: 'Empuje', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Press pecho con goma', s: '3×12' },
        { n: 'Press hombro', s: '3×12' },
        { n: 'Elevaciones laterales', s: '3×12' },
        { n: 'Tríceps goma', s: '3×12' },
        { n: 'Tríceps overhead', s: '2×12' },
      ]},
      { nombre: 'Martes', tag: 'Tirón', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Remo', s: '3×12' },
        { n: 'Jalón', s: '3×12' },
        { n: 'Curl bíceps', s: '3×12' },
        { n: 'Trapecio', s: '3×15' },
        { n: 'Face pull', s: '3×12' },
      ]},
      { nombre: 'Miércoles', tag: '', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Plancha', s: '2×20 s' },
        { n: 'Bird-dog', s: '2×10/lado' },
        { n: 'Press pecho', s: '2×12' },
        { n: 'Remo', s: '2×12' },
      ]},
      { nombre: 'Jueves', tag: 'Movilidad', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Respiración', s: '2 min' },
        { n: 'Movilidad tobillo', s: '2×20' },
        { n: 'Rotación tobillo', s: '2×15' },
        { n: 'Gato-vaca', s: '2×10' },
        { n: 'Rotación torácica', s: '2×8/lado' },
        { n: 'Círculos cadera', s: '2×10' },
        { n: 'Elevación pierna', s: '2×10' },
        { n: 'Wall slides', s: '2×10' },
        { n: 'Estiramientos', s: '20–30 s' },
      ]},
      { nombre: 'Viernes', tag: 'Pierna', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Sentadilla', s: '2×10' },
        { n: 'Puente', s: '2×15' },
        { n: 'Curl femoral', s: '2×12' },
        { n: 'Abducción', s: '2×12' },
      ]},
      { nombre: 'Sábado', tag: '', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Bisagra', s: '2×12' },
        { n: 'Puente', s: '2×15' },
        { n: 'Press pecho', s: '2×12' },
        { n: 'Remo', s: '2×12' },
      ]},
      { nombre: 'Domingo', tag: 'Circuito', ejercicios: [
        { n: 'Bici', s: '20 min' },
        { n: 'Sentadilla', s: '×10 (2 vueltas)' },
        { n: 'Press hombro', s: '×12 (2 vueltas)' },
        { n: 'Remo', s: '×12 (2 vueltas)' },
        { n: 'Puente', s: '×15 (2 vueltas)' },
        { n: 'Curl femoral', s: '×12 (2 vueltas)' },
        { n: 'Plancha', s: '20 s (2 vueltas)' },
      ]},
    ]
  },
  2: {
    label: 'Semana 2',
    libres: [3, 4],
    dias: [
      { nombre: 'Lunes', tag: '', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Bisagra', s: '2×12' },
        { n: 'Puente', s: '2×15' },
        { n: 'Press pecho', s: '2×12' },
        { n: 'Remo', s: '2×12' },
      ]},
      { nombre: 'Martes', tag: 'Descanso', ejercicios: [
        { n: 'Descanso total', s: '' },
      ]},
      { nombre: 'Miércoles', tag: 'Empuje', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Press pecho con goma', s: '3×12' },
        { n: 'Press hombro', s: '3×12' },
        { n: 'Elevaciones laterales', s: '3×12' },
        { n: 'Tríceps goma', s: '3×12' },
        { n: 'Tríceps overhead', s: '2×12' },
      ]},
      { nombre: 'Jueves', tag: 'Tirón', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Remo', s: '3×12' },
        { n: 'Jalón', s: '3×12' },
        { n: 'Curl bíceps', s: '3×12' },
        { n: 'Trapecio', s: '3×15' },
        { n: 'Face pull', s: '3×12' },
      ]},
      { nombre: 'Viernes', tag: 'Pierna', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Sentadilla', s: '2×10' },
        { n: 'Puente', s: '2×15' },
        { n: 'Curl femoral', s: '2×12' },
        { n: 'Abducción', s: '2×12' },
      ]},
      { nombre: 'Sábado', tag: 'Movilidad', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Respiración', s: '2 min' },
        { n: 'Movilidad tobillo', s: '2×20' },
        { n: 'Rotación tobillo', s: '2×15' },
        { n: 'Gato-vaca', s: '2×10' },
        { n: 'Rotación torácica', s: '2×8/lado' },
        { n: 'Círculos cadera', s: '2×10' },
        { n: 'Elevación pierna', s: '2×10' },
        { n: 'Wall slides', s: '2×10' },
        { n: 'Estiramientos', s: '20–30 s' },
      ]},
      { nombre: 'Domingo', tag: 'Circuito', ejercicios: [
        { n: 'Bici', s: '20 min' },
        { n: 'Sentadilla', s: '×10 (2 vueltas)' },
        { n: 'Press hombro', s: '×12 (2 vueltas)' },
        { n: 'Remo', s: '×12 (2 vueltas)' },
        { n: 'Puente', s: '×15 (2 vueltas)' },
        { n: 'Curl femoral', s: '×12 (2 vueltas)' },
        { n: 'Plancha', s: '20 s (2 vueltas)' },
      ]},
    ]
  },
  3: {
    label: 'Semana 3',
    libres: [4, 5],
    dias: [
      { nombre: 'Lunes', tag: '', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Plancha', s: '2×20 s' },
        { n: 'Bird-dog', s: '2×10/lado' },
      ]},
      { nombre: 'Martes', tag: 'Movilidad', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Respiración', s: '2 min' },
        { n: 'Movilidad tobillo', s: '2×20' },
        { n: 'Rotación tobillo', s: '2×15' },
        { n: 'Gato-vaca', s: '2×10' },
        { n: 'Rotación torácica', s: '2×8/lado' },
        { n: 'Círculos cadera', s: '2×10' },
        { n: 'Elevación pierna', s: '2×10' },
        { n: 'Wall slides', s: '2×10' },
        { n: 'Estiramientos', s: '20–30 s' },
      ]},
      { nombre: 'Miércoles', tag: 'Pierna', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Sentadilla', s: '2×10' },
        { n: 'Puente', s: '2×15' },
        { n: 'Curl femoral', s: '2×12' },
        { n: 'Abducción', s: '2×12' },
      ]},
      { nombre: 'Jueves', tag: 'Empuje', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Press pecho con goma', s: '3×12' },
        { n: 'Press hombro', s: '3×12' },
        { n: 'Elevaciones laterales', s: '3×12' },
        { n: 'Tríceps goma', s: '3×12' },
        { n: 'Tríceps overhead', s: '2×12' },
      ]},
      { nombre: 'Viernes', tag: 'Tirón', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Remo', s: '3×12' },
        { n: 'Jalón', s: '3×12' },
        { n: 'Curl bíceps', s: '3×12' },
        { n: 'Trapecio', s: '3×15' },
        { n: 'Face pull', s: '3×12' },
      ]},
      { nombre: 'Sábado', tag: '', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Bisagra', s: '2×12' },
        { n: 'Puente', s: '2×15' },
        { n: 'Press pecho', s: '2×12' },
        { n: 'Remo', s: '2×12' },
      ]},
      { nombre: 'Domingo', tag: 'Descanso', ejercicios: [
        { n: 'Descanso total', s: '' },
      ]},
    ]
  },
  4: {
    label: 'Semana 4',
    libres: [6, 0],
    dias: [
      { nombre: 'Lunes', tag: '', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Bisagra', s: '2×12' },
        { n: 'Puente', s: '2×15' },
      ]},
      { nombre: 'Martes', tag: 'Movilidad', ejercicios: [
        { n: 'Bici', s: '15 min' },
        { n: 'Respiración', s: '2 min' },
        { n: 'Movilidad tobillo', s: '2×20' },
        { n: 'Rotación tobillo', s: '2×15' },
        { n: 'Gato-vaca', s: '2×10' },
        { n: 'Rotación torácica', s: '2×8/lado' },
        { n: 'Círculos cadera', s: '2×10' },
        { n: 'Elevación pierna', s: '2×10' },
        { n: 'Wall slides', s: '2×10' },
        { n: 'Estiramientos', s: '20–30 s' },
      ]},
      { nombre: 'Miércoles', tag: 'Pierna', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Sentadilla', s: '2×10' },
        { n: 'Puente', s: '2×15' },
        { n: 'Curl femoral', s: '2×12' },
        { n: 'Abducción', s: '2×12' },
      ]},
      { nombre: 'Jueves', tag: '', ejercicios: [
        { n: 'Bici', s: '15–20 min' },
        { n: 'Plancha', s: '2×20 s' },
        { n: 'Bird-dog', s: '2×10/lado' },
        { n: 'Press pecho', s: '2×12' },
        { n: 'Remo', s: '2×12' },
      ]},
      { nombre: 'Viernes', tag: 'Descanso', ejercicios: [
        { n: 'Descanso total', s: '' },
      ]},
      { nombre: 'Sábado', tag: 'Empuje', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Press pecho con goma', s: '3×12' },
        { n: 'Press hombro', s: '3×12' },
        { n: 'Elevaciones laterales', s: '3×12' },
        { n: 'Tríceps goma', s: '3×12' },
        { n: 'Tríceps overhead', s: '2×12' },
      ]},
      { nombre: 'Domingo', tag: 'Tirón', ejercicios: [
        { n: 'Bici', s: '30 min' },
        { n: 'Remo', s: '3×12' },
        { n: 'Jalón', s: '3×12' },
        { n: 'Curl bíceps', s: '3×12' },
        { n: 'Trapecio', s: '3×15' },
        { n: 'Face pull', s: '3×12' },
      ]},
    ]
  },
};
